name: CD

on:
  push:
    branches:
      - master

permissions:
  contents: read
  packages: write

jobs:
  docker:
    name: Build & Push — ${{ matrix.service }}
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        service:
          - api-gateway
          - user-service
          - catalog-service
          - order-service
          - payment-service
          - inventory-service
          - shipping-service
          - notification-service

    steps:
      - uses: actions/checkout@v4

      # Set short commit SHA for versioning
      - name: Set image tag
        run: echo "IMAGE_TAG=${GITHUB_SHA::7}" >> $GITHUB_ENV

      # Login to GHCR
      - name: Login to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      # Setup Buildx
      - name: Setup Docker Buildx
        uses: docker/setup-buildx-action@v3

      # Build & Push
      - name: Build & Push Docker Image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: apps/${{ matrix.service }}/Dockerfile
          push: true

          build-args: |
            SERVICE=${{ matrix.service }}

          tags: |
            ghcr.io/sethava/nest-monorepo-ecommerce/${{ matrix.service }}:latest
            ghcr.io/sethava/nest-monorepo-ecommerce/${{ matrix.service }}:${{ env.IMAGE_TAG }}

          cache-from: type=gha
          cache-to: type=gha,mode=max